SEQUENCE = [
    "NAVIGATE_TO_ANTENNA_AREA",
    "FIND_HIGHEST_POINT",
    "NAVIGATE_TO_SHACKLETON_CRATER",
    "SEARCH_DARK_ROCKS",
    "NAVIGATE_TO_LAVA_TUBE",
    "MEASURE_LAVA_TUBE",
    "RETURN_TO_AIRLOCK",
]

WAYPOINTS = {
    "NAVIGATE_TO_ANTENNA_AREA":       (5.0, -10.0),
    "NAVIGATE_TO_SHACKLETON_CRATER":  (20.0, -30.0),
    "NAVIGATE_TO_LAVA_TUBE":          (0.0, -15.0),
    "RETURN_TO_AIRLOCK":              (10.0, 0.0),
}
