#!/usr/bin/env python3
"""
Sequence:
  1. BOOTING           
  2. NAVIGATE_TO_SENSOR_ZONE_1
  3. DELIVER_RECORDER
  4. NAVIGATE_TO_SENSOR_ZONE_2
  5. DELIVER_SENSORS 
  6. NAVIGATE_TO_PANEL_ZONE
  7. NAVIGATE_TO_PIPE_ZONE       
  8. NAVIGATE_TO_MIRROR_ZONE
  9. NAVIGATE_TO_ANTENNA_ZONE
 10. NAVIGATE_TO_LAVA_ZONE
 11. DOME_RETURN
 12. SEQUENCE_COMPLETE
"""

